### PR TITLE
inflect negative numbers correctly

### PR DESCRIPTION
**Pull request by Mic92**
fixes https://github.com/mozilla/TTS/issues/587

### CODE REVIEW

**Comment by Mic92** [comment]
Any comments on this change?

**Comment by erogol** [comment]
Can you write a test about it in test_text_processing.py?

**Comment by Mic92** [comment]
I added one test but it seems like in dev all the other tests in text_processing are broken now:

```
FAILED tests/test_text_processing.py::test_phoneme_to_sequence - AssertionError: assert 'ɹiːsənt ɹᵻsɜ...n ænd lɜːnɪŋ!' == 'ɹiːsənt ɹɪsɜ...n ænd lɜːnɪŋ!'
FAILED tests/test_text_processing.py::test_phoneme_to_sequence_with_blank_token - AssertionError: assert 'ɹiːsənt ɹᵻsɜ...n ænd lɜːnɪŋ!' == 'ɹiːsənt ɹɪsɜ...n ænd lɜːnɪŋ!'
FAILED tests/test_text_processing.py::test_text2phone - AssertionError:
```

Do you run tests?

**Comment by Mic92** [comment]
I don't see pull requests here: https://app.circleci.com/pipelines/github/mozilla/TTS

**Comment by Mic92** [comment]
https://github.com/mozilla/TTS/pull/597

**Pull request closed without merging**
