### PR TITLE
renamed attention_rnn to query_rnn

### PR DESCRIPTION
**Pull request by twerkmeister**
I renamed attention_rnn in Taco1 and Taco2 decoders to query_rnn to avoid the confusion with the attention layer. At least personally I had my head spinning distinguishing attention_rnn, attention_rnn_hidden, attention_layer, attention, etc.  

I think this naming change makes more clear that there is a part generating the query and then the attention part that uses the query. Especially since `attention_rnn_hidden` turned to `query` inside the attention layer at some point already.

Other changes that you should specifically look at:
1. In forward attention: moved the to_device to directly after the cloning, not after padding
2. in forward attention: removed the cloning where the alpha tensor is just multiplied with the u tensor
3. in tacotron - decoder - decode: removed the del statements. I believe this is not saving memory since a) you just created another reference beforehand without cloning, and b) the tensors have to be kept around for back prop. Also, invoking the garbage collector inside the training loop might cost performance

### CODE REVIEW

**Comment by erogol** [comment]
except for attention_rnn I am fine with renaming. Attention_rnn is the name touted by its paper, therefore it is better to keep it as it is. In the end, it is attention for rnn.

**Comment by erogol** [comment]
Can you plealse train this with a small dataset to check if it converges? Sometimes renaming can break things with a hazy eye.

**Comment by twerkmeister** [comment]
jup will run a test today

**Comment by twerkmeister** [comment]
hm the last change occured to me, it seems to make more sense to update location attention with the actual attention used after computing fwd attention, doesn't it? Otherwise attention_cum isn't recording the actually used attention

**Comment by erogol** [comment]
I've tried the way you suggested but it did not work before. Location attention should see real attention weights.

**Comment by twerkmeister** [comment]
Ran experiments with both setups and both learned attention, but location attn before fwd attention seemed to perform better during inference

**Pull request merged**
