### PR TITLE
Add Dutch model

### PR DESCRIPTION
**Pull request by r-dh**

### CODE REVIEW

**Comment by tijder** [comment]
Nice work getting a Dutch TTS working! 

I got an error when trying to use this model with this command:
```
tts --text "Test" \
    --model_name "tts_models/nl/mai/tacotron2-DDC" \
    --vocoder_name "vocoder_models/universal/libri-tts/fullband-melgan" \
    --out_path /out/
```

Console output:
```
2021-03-01 19:23:53.378792: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-03-01 19:23:53.378820: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 > Downloading model to /root/.local/share/tts/tts_models--nl--mai--tacotron2-DDC
Downloading...
From: https://drive.google.com/uc?id=1cJWpKflkvchVidn0oyUZdv9CPDOUMi_Q
To: /root/.local/share/tts/tts_models--nl--mai--tacotron2-DDC/model_file.pth.tar
575MB [00:58, 9.77MB/s] 
Downloading...
From: https://drive.google.com/uc?id=1SY61VgvMNafrb76BgxP-ulsG8rhTE1we
To: /root/.local/share/tts/tts_models--nl--mai--tacotron2-DDC/config.json
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.7k/10.7k [00:00<00:00, 23.2MB/s]
 > vocoder_models/universal/libri-tts/fullband-melgan is already downloaded.
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:55.0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:None
 | > hop_length:256
 | > win_length:1024
 > Using model: Tacotron2
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/TTS/bin/synthesize.py", line 177, in main
    synthesizer = Synthesizer(model_path, config_path, vocoder_path, vocoder_config_path, args.use_cuda)
  File "/usr/local/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 46, in __init__
    self.load_tts(tts_checkpoint, tts_config,
  File "/usr/local/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 92, in load_tts
    self.tts_model = setup_model(self.input_size, num_speakers=self.num_speakers, c=self.tts_config)
  File "/usr/local/lib/python3.8/site-packages/TTS/tts/utils/generic_utils.py", line 88, in setup_model
    gst_use_speaker_embedding=c.gst['gst_use_speaker_embedding'],
KeyError: 'gst_use_speaker_embedding'
```

**Comment by r-dh** [comment]
You can check the config over here: https://drive.google.com/file/d/1SY61VgvMNafrb76BgxP-ulsG8rhTE1we

Perhaps it could be fixed by renaming the "use_speaker_embedding" dict entry to "gst_use_speaker_embedding", although I haven't tested that myself. You're likely to run into a couple more minor errors along the way.

I'd recommend checking out the commit on which this model was trained, which is `540d811`

**Comment by tijder** [comment]
Thanks for your help. I couldn't get it to working. Maybe someone else can get it working on latest commit.

**Comment by r-dh** [comment]
I've adapted and created this [colab](https://colab.research.google.com/drive/1PNPi2z3VNepbTH-IK2uZCkgpkwT_IowW?usp=sharing) based on the German model notebook. Perhaps this might help you a bit further.

**Pull request closed without merging**
