### PR TITLE
Corrected GMMv2b attention model

### PR DESCRIPTION
**Pull request by geneing**
Per discussion on discourse forum, this is the corrected implementation of GMMv2b model. I also cleaned up code by using parametrized ranges.

### CODE REVIEW

**Comment by erogol** [comment]
great thx. I'll check how it performs asap.

**Comment by erogol** [comment]
@geneing Do you use the default config for your experiment?

**Comment by erogol** [comment]
from the initial look after 40K, this PR looks better than the previous graves. Thx again for it @geneing

**Comment by geneing** [comment]
> @geneing Do you use the default config for your experiment?

I tested on mailabs dataset, so sample_rate was set to 16000, and attention was set to graves. Other, everything from config.json in the dev branch.

**Comment by erogol** [comment]
@geneing on ljspeech it looks good so far but the final spectrograms are low in quality compared to previous version. Especially beginnings and endings are poor.

**Comment by alexdemartos** [comment]
Hi @geneing , thanks for your contribution. Just ported your GMMv2b implementation to Tensorflow. It seems to work pretty well (alignment is learnt even before 5K steps, and looks absolutely fine). Nevertheless, I am running on sudden loss explosion shortly after the alignment is learnt (4K - 6K steps). Did this happen before to you? Do you have any idea why this might happen or any suggestions how to solve it?

**Pull request merged**
