### PR TITLE
Issue#110

### PR DESCRIPTION
**Pull request by gnosly**
Hi,
i tried to solve the issue #110 . With this PR I propose you to add a new model config parameter called `input_chars` that identifies the inputs of the Tacotron Embedding layer.

### CODE REVIEW

**Comment by erogol** [comment]
I think it is better to compute num_chars the same way here https://github.com/mozilla/TTS/blob/master/train.py#L390
otherwise, the change here violates the code part above.

**Comment by gnosly** [comment]
Hi Eren,
I've thought to use the logic as you suggested but it doesn't convince me because, if I've understood correctly, the phoneme and symbol dictionaries could change in the future, but the model itself depends on the phoneme or symbol dictionaries used to train.
it should be nice to have a model package that contains all the required information so that we can run the model with the latest sources. It's not so intuitive to checkout a specific revision in order to try a model.
Do you think it could be feasable? 

Anyway feel free to reject the PR if you think it is not useful.

**Comment by erogol** [comment]
@gnosly you are definitely right. But TTS is not officially released yet and there are many core changes day to day so it is almost impossible to keep it user ready for now. That's why, I keep the commit revisions as a way to reuse trained models. However, if you have any suggestion to deal with such a surge, please let me know. 

I think the best way to deal with symbols is to use utf-8 codes instead of characters. This way, we don't need to worry about character changes between languages. In phoneme mode, I am just lazy to list all the phonemes in ```symbols.py```. Therefore, I programmatically count related phonemes per language and update ```symbols.py``` accordingly. However, if one places all possible phonemes in the file, then no need to edit for different languages, if you are not worried about the size of the embedding layer.

**Comment by gnosly** [comment]
Hi @erogol, 
I would like to help you but I'm newbie in this context. Anyway I try:

If I've understood well you are using IPA phonetic symbols because phonemizer is executed as 
`'espeak -ven-us -x --ipa -q ......`

So I could add the phonetic symbols presented here

https://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm#alfa

into `symbols.py`

Right?

What I've not understood yet is why the symbols added by @mozillakab are not presented in the list above.

**Comment by rnunziata** [comment]
when will this be fixed I have the same issue with checkpoints from current links.

**Comment by erogol** [comment]
@gnosly yes I think we can try this to include. I don't know how compatible with espeak but we can try. Thanks for your intend to deal with it.

**Comment by erogol** [comment]
@rnunziata you can always use checkpoints with the right commit version given at the table.

**Comment by rnunziata** [comment]
so I downloaded the checkpoint and its assocated commit 

Commit and checkpoint for: " Stop-Token prediction is added, to detect end of speech."

and get the same error running  TacotronPlayGround after changing the checkpoint in the code to checkpoint_272976.pth.tar  

`	size mismatch for decoder.stopnet.linear.weight: copying a param of torch.Size([1, 281]) from checkpoint, where the shape is torch.Size([1, 400]) in current model.`

**Comment by rnunziata** [comment]
Does anyone have a current link to a checkpoint for the current master branch that can be used in the notebook scripts like TacotronPlayGround

**Comment by nmstoker** [comment]
I don't believe I'm doing anything wrong, yet I still get the size mismatch errors even though I've checked out the matching commit (db7f3d3) that corresponds with the model I downloaded (the most recent one, last in the table) and then gone ahead with all the other steps in the server README prior to building the docker image (including making the model available within the image).

Also I tried it without docker (ie directly, using a conda environment with the repo checked out at the corresponding commit) and get the same errors, so I don't _think_ it's a docker specific thing.

Any advice @erogol ? Is there something about that final model?

**Comment by gnosly** [comment]
This PR is obsolete.

**Pull request closed without merging**
