### PR TITLE
fixed config comment strings for attention parameters

### PR DESCRIPTION
**Pull request by twerkmeister**
comments in the config files were still stating that attention parameters only applied to Taco2 models although both taco1 and taco2 now have a shared attention layer

### CODE REVIEW

**Comment by twerkmeister** [comment]
Travis seems to fail during some pip commands for the setup

**Comment by erogol** [comment]
if you rebase last two PRs they will pass Travis.

**Comment by twerkmeister** [comment]
rebase to where?

**Comment by reuben** [comment]
Latest master, or really anything after commit b1657d70b160c097be7ac24290514a9aed010452, which should fix it.

**Comment by twerkmeister** [comment]
that was quick ^^

**Pull request merged**
