### PR TITLE
Add support for external embeddings

### PR DESCRIPTION
**Pull request by george-roussos**
In the form of txt file. If it must be on the dev branch it is ok

### CODE REVIEW

**Comment by erogol** [comment]
thx for the PR. It is really useful but please consider fixing travis errors and writing some tests for your addition.

**Comment by george-roussos** [comment]
Where does the Travis TTS test pull Tacotron2 from? Because I have added `external_embeddings` in `__init__`.

**Comment by erogol** [comment]
it install TTS using setup.py and then calls things as it is supposed to call. Nothing fancy.

**Comment by erogol** [comment]
don't stale :)

**Pull request closed without merging**
