### PR TITLE
added missing phonemes, synthesizer.py now setup the correct input layer

### PR DESCRIPTION
**Pull request by gnosly**

### CODE REVIEW

**Comment by erogol** [comment]
Great pr thx !

**Comment by erogol** [comment]
@gnosly testing, in case,  with a new training

**Comment by gnosly** [comment]
@erogol Great! Happy to be useful. I would like to train the model but I've not got a Nvidia. I don't know how much training on AWS with a GPU EC2 cost. Do you think it could be feasable? How long 100k iterations take?

**Comment by erogol** [comment]
@gnosly around 4 days with a single GPU and 32 batch size

**Comment by erogol** [comment]
@gnosly it works!! thx again !!

**Comment by gnosly** [comment]
Perfect! Are there improvements on sound quality?

Fabrizio

**Comment by erogol** [comment]
@gnosly sound quality has not been changed so much but on par with the previous version for English.

**Pull request merged**
