### PR TITLE
Support for Mutlispeaker Tacotron2 with GST and the ability to condition on tokens

### PR DESCRIPTION
**Pull request by SanjaESC**
GST style input can be conditioned either on wav file or tokens 
- If using tokens you need to pass a dictionary with the tokens you want to modify to "gst_style_input" in the config.
- Example: {"0": 0.15, "1": 0.15, "5": -0.15}  Key=Token 
- Where the dictionary being len(dict) <= len(gst_style_tokens).

### CODE REVIEW

**Comment by SanjaESC** [comment]
maybe it's better to create an alternative model?

**Comment by erogol** [comment]
why did you close this one?

**Comment by erogol** [comment]
It'd be good to have two new test cases in test_tacotron_model.py and test_tacotron2_model.py testing inference with different style input settings (input wav and style token weights).

**Comment by erogol** [comment]
@Edresson it'd be nice you to review this PR since you also implement similar things.

**Comment by Edresson** [comment]
@erogol  Thanks. I reviewed the PR, and everything is Ok, in my branch I did something very similar :).

**Comment by Edresson** [comment]
@SanjaESC I implemented the  GST tests and fixed some bugs that I found in this PR and added to the PR #472

**Comment by SanjaESC** [comment]
@Edresson Nice! This one can be closed then?

**Comment by Edresson** [comment]
Yes you can close it your committees have been added in the dev branch :)

**Pull request closed without merging**
