### PR TITLE
add text parameters in config.json

### PR DESCRIPTION
**Pull request by Edresson**
Added suggestion for [issue 355](https://github.com/mozilla/TTS/issues/355).

### CODE REVIEW

**Comment by erogol** [comment]
THX for the PR. You have two PR which one should I consider? Also please fix the Travis errors.

**Comment by Edresson** [comment]
@erogol  I fixed the Travis errors and closed the other pull request.

**Comment by erogol** [comment]
Thanks. PR looks ok to me. But instead of ```text``` i think ```characters``` is a better name in the config file.

**Comment by Edresson** [comment]
I made the changes and everything seems to work fine.

**Comment by Edresson** [comment]
@erogol  Do you suggest any more changes?

**Comment by erogol** [comment]
We also need a unittest for this. You can add your text inputs in a mock config and compare text_to_sequence and phoneme_to_senquence results of using the default charset and if you give the same charset in that mock config. 

I just want to make sure that things are safe and sound before putting this change forward.

**Comment by Edresson** [comment]
@erogol  Do you think it is appropriate to add these tests in  `tests/test_text_processing.py`
 using the texts already present in this file just adding the calls to `phoneme_to_sequence` 
and `sequence_to_phoneme` passing in mock config (test_config.json)?

**Comment by erogol** [comment]
exactly it would be the best place for these tests. It is better to keep the config file separate for this since it might break the other tests.

**Comment by Edresson** [comment]
@erogol I implemented it in the same conf file and did not break any tests, do you think this is good enough?

**Comment by erogol** [comment]
@Edresson thx things looks nice now.

**Pull request merged**
